# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from abc import ABC, abstractmethod
from typing import cast, List, Tuple
import torch
import torch.nn.functional as F
from torch import Tensor
from einops import rearrange
from torchtyping import TensorType as T
from reasyn.chem.featurize import TokenType


def x2prob(x: Tensor, vocab_size: int) -> Tensor:
    """Converts sequence of tokens to class distribution representation
    """
    return torch.nn.functional.one_hot(x, num_classes=vocab_size).float()


def sample_p(pt: Tensor, temperature: float = 1.0) -> Tensor:
    """Samples protein sequence from class distribution representation
    """
    b, l, _ = pt.shape
    pt = rearrange(pt, 'b l c -> (b l) c')
    xt = torch.multinomial(pt / temperature, 1)
    return xt.reshape(b, l)


class Coupling(ABC):
    @abstractmethod
    def sample(self, x1: Tensor) -> tuple[Tensor, Tensor]:
        raise NotImplementedError


class EmptyCoupling(Coupling):
    """A coupling that samples empty prior sequences
    """
    def sample(self, x1: Tensor, restore_bos: bool = True):
        if restore_bos:
            x0 = torch.full((x1.shape[0], 1), TokenType.START, dtype=x1.dtype, device=x1.device)
        else:
            x0 = torch.empty((x1.shape[0], 0), dtype=x1.dtype, device=x1.device).long()
        return x0

    def sample_and_align(self, x1: Tensor, restore_bos: bool = True):
        x0 = self.sample(x1, restore_bos)
        z0, z1 = align_x2z(x0, x1)
        return z0, z1


class UniformCoupling(Coupling):
    """A coupling that samples uniform prior sequences within a given length range
    """
    def __init__(
        self,
        vocab_size: int,
        min_len: int = 0,
        max_len: int = 256,
    ):
        self.min_len = min_len
        self.max_len = max_len
        self.vocab_size = vocab_size
        
    def sample(self, x1: Tensor, restore_bos: bool = True):
        batch_size = x1.shape[0]
        x0_seq_len = torch.randint(self.min_len, self.max_len + 1, size=(batch_size,)).long()
        x0_max_len = int(x0_seq_len.max().item())
        x0_pad_mask = torch.arange(x0_max_len).expand(batch_size, -1) >= x0_seq_len.unsqueeze(-1)

        x0 = torch.randint(0, self.vocab_size, size=(batch_size, x0_max_len), dtype=x1.dtype, device=x1.device)
        x0[x0_pad_mask] = TokenType.END
        if restore_bos:
            x0[:, 0] = TokenType.START
        return x0


class BridgeCoupling(Coupling):
    """A coupling that uses sequences generated by a pretrained model as prior
    """
    def _sample_token(self, model, tokens, code, code_padding_mask, temperature_token=0.1):
        logits = model.sample(
            code=code,
            code_padding_mask=code_padding_mask,
            tokens=tokens,
            token_padding_mask=None)
        next_token = torch.multinomial(
            torch.nn.functional.softmax(logits / temperature_token, dim=-1),
            num_samples=1,
        )
        return next_token
    
    @torch.inference_mode()
    def sample(self, model, smiles: Tensor):
        bsz = smiles.shape[0]
        code, code_padding_mask = model.encoder(smiles)
        tokens = torch.full((bsz, 1), TokenType.START).to(smiles.device)
        finished = torch.zeros(bsz).byte()
        for _ in range(model.max_len - 1):
            next_token = self._sample_token(model, tokens, code, code_padding_mask)
            tokens = torch.hstack([tokens, next_token])
            is_eos = (next_token.squeeze(-1) == TokenType.END).cpu()
            finished = torch.ge(finished + is_eos, 1)
            if finished.prod() == 1: break
        return tokens
        

def get_coupling(coupling_type: str, **kwargs):
    if coupling_type == 'empty':
        return EmptyCoupling()
    elif coupling_type == 'uniform':
        return UniformCoupling(**kwargs)
    elif coupling_type == 'bridge':
        return BridgeCoupling()
    else:
        raise ValueError('Wrong couling_type!')
    

class KappaScheduler:
    def __init__(self, scheduler_type: str):
        self.type = scheduler_type
        if self.type not in ('cubic', 'square', 'linear'):
            raise ValueError('Wrong schedule_type!')

    def __call__(self, t: Tensor) -> Tensor:
        if self.type == 'cubic':
            return t ** 3
        elif self.type == 'square':
            return t ** 2
        else:
            return t

    def derivative(self, t: Tensor) -> Tensor:
        if self.type == 'cubic':
            return 3 * t ** 2
        elif self.type == 'square':
            return 2 * t
        else:
            return 1


def sample_cond_pt(p0: torch.Tensor, p1: torch.Tensor, t: torch.Tensor, kappa: KappaScheduler):
    t = t.reshape(-1, 1, 1)
    pt = (1 - kappa(t)) * p0 + kappa(t) * p1
    return sample_p(pt)


def make_batch(
    x1: torch.Tensor,
    z0: torch.Tensor,
    z1: torch.Tensor,
    vocab_size: int,
    scheduler: KappaScheduler,
):
    z0 = torch.where(z1 == TokenType.END, TokenType.END, z0)    # restore PAD tokens
    t = torch.rand(x1.shape[0], 1).to(x1.device)

    p0 = x2prob(z0, vocab_size + 1) # +1 for GAP (EPS) token
    p1 = x2prob(z1, vocab_size + 1)
    zt = sample_cond_pt(p0, p1, t, scheduler)   # interpolates in Z space
    xt, x_pad_mask, z_gap_mask, z_pad_mask = rm_gap_tokens(zt)  # removes GAP and PAD tokens to max length
    
    # uz_mask indicates which operations bring zt closer to z1
    uz_mask = make_ut_mask_from_z(
        cast(T["batch_size", "z_seq_len", "long"], zt),
        cast(T["batch_size", "z_seq_len", "long"], z1),
        vocab_size = vocab_size,
    )   # batch_size, z_seq_len, 2 * vocab_size + 1
    return xt, x_pad_mask, t, uz_mask, z_gap_mask, z_pad_mask


def make_ut_mask_from_z(
    zt: T["batch_size", "z_seq_len", "long"],
    z1: T["batch_size", "z_seq_len", "long"],
    vocab_size: int,
    ) -> T["batch_size", "z_seq_len", "n_ops", "bool"]:
    """
    Create a mask for u_cat for indexing the output rate tensor based on differences between z_t and z_1.
    For each position i where z_t and z_1 differ, we index as follows:

    - zt[i] = GAP_TOKEN & z1[i] = c => u_mask[i, insert, c] = 1
    - zt[i] = c & z1[i] = GAP_TOKEN => u_mask[i, delete] = 1
    - zt[i] = c1 & z1[i] = c2 => u_mask[i, substitute, c1, c2] = 1
    """
    batch_size, z_seq_len = zt.shape
    n_ops = 2 * vocab_size + 1  # insert + substitute + delete

    z_neq = (zt != z1) & (zt != TokenType.END) & (z1 != TokenType.END)
    z_ins = (zt == TokenType.EPS) & (z1 != TokenType.EPS) & z_neq     # (batch_size, z_seq_len)
    z_del = (zt != TokenType.EPS) & (z1 == TokenType.EPS) & z_neq     # (batch_size, z_seq_len)
    z_sub = z_neq & ~z_ins & ~z_del                                     # (batch_size, z_seq_len) 

    # mask (batch_size, z_seq_len, u_ops) where 1 indicates operation that bring z_t closer to z_1
    u_mask = torch.zeros((batch_size, z_seq_len, n_ops), dtype=torch.bool, device=zt.device)
    u_mask[z_ins, z1[z_ins]] = True
    u_mask[z_sub, z1[z_sub] + vocab_size] = True
    u_mask[:,:,-1][z_del] = True

    assert z_neq.sum() == (z_ins | z_del | z_sub).sum(), "Mismatch in number of edits"
    assert z_neq.sum() == u_mask.sum(), "Mismatch in number of edits in mask"

    return cast(T["batch_size", "z_seq_len", "n_ops", "bool"], u_mask)


def fill_gap_tokens_with_repeats(
    x_ut: torch.Tensor,
    z_gap_mask: torch.Tensor,
    z_pad_mask: torch.Tensor,
    ):
    batch_size, _ = z_gap_mask.shape
    _, x_seq_len, _ = x_ut.shape

    # Use cumsum on non-gap positions to point to the last valid non-gap position
    non_gap_mask = ~z_gap_mask  # Invert mask to get non-gap positions
    indices = non_gap_mask.cumsum(dim=1) - 1        # (batch_size, z_seq_len)
    indices = indices.clamp(min=0, max=x_seq_len-1) # Ensure indices are within bounds

    # Use indices to gather from x_ut
    batch_indices = torch.arange(batch_size, device=x_ut.device).unsqueeze(1)
    result = x_ut[batch_indices, indices]   # (batch_size, z_seq_len, vocab_size)
    result[z_pad_mask] = 0                  # Set pad positions to 0
    return result


def _align_pair(seq_0: torch.Tensor, seq_1: torch.Tensor) -> Tuple[List[int], List[int]]:
    """
    Aligns two sequences using dynamic programming to find the minimum edit distance.
    Returns two lists representing the aligned sequences.
    """
    seq_0, seq_1 = seq_0.cpu().numpy(), seq_1.cpu().numpy()
    m, n = len(seq_0), len(seq_1)
    
    # DP table
    dp = [[i + j if i == 0 or j == 0 else 0 for j in range(n + 1)] for i in range(m + 1)]
    for i in range(1, m + 1):
        for j in range(1, n + 1):
            dp[i][j] = dp[i-1][j-1] if seq_0[i-1] == seq_1[j-1] else 1 + min(dp[i-1][j], dp[i][j-1], dp[i-1][j-1])
    
    # Backtrack
    aligned_0, aligned_1 = [], []
    i, j = m, n
    while i or j:
        if i and j and seq_0[i-1] == seq_1[j-1]:
            aligned_0.append(seq_0[i-1])
            aligned_1.append(seq_1[j-1])
            i, j = i-1, j-1
        elif i and j and dp[i][j] == dp[i-1][j-1] + 1:
            aligned_0.append(seq_0[i-1])
            aligned_1.append(seq_1[j-1])
            i, j = i-1, j-1
        elif i and dp[i][j] == dp[i-1][j] + 1:
            aligned_0.append(seq_0[i-1])
            aligned_1.append(TokenType.EPS)
            i -= 1
        else:
            aligned_0.append(TokenType.EPS)
            aligned_1.append(seq_1[j-1])
            j -= 1
    return aligned_0[::-1], aligned_1[::-1]


def align_x2z(x_0: torch.Tensor, x_1: torch.Tensor) -> Tuple[torch.Tensor, torch.Tensor]:
    """
    Aligns x_0 and x_1 to the same length by using a dynamic programming approach
    to find the minimum edit distance alignment.
    """
    aligned_pairs = [_align_pair(x_0[b], x_1[b]) for b in range(x_0.shape[0])]
    x_0_aligned = torch.stack(
        [torch.tensor(pair[0], dtype=x_0.dtype, device=x_0.device) for pair in aligned_pairs])
    x_1_aligned = torch.stack(
        [torch.tensor(pair[1], dtype=x_1.dtype, device=x_1.device) for pair in aligned_pairs])
    return x_0_aligned, x_1_aligned


def rm_gap_tokens(z: torch.Tensor) -> Tuple[torch.Tensor, torch.Tensor, torch.Tensor, torch.Tensor]:
    """
    Remove gap tokens from a batched tensor and right-pad with PAD_TOKEN (TokenType.END).
    """    
    batch_size, _ = z.shape
    z_no_gap = []
    for b in range(batch_size):
        z_no_pad = z[b][z[b] != TokenType.END]
        z_no_gap.append(z_no_pad[z_no_pad != TokenType.EPS])
    max_len = max(len(z) for z in z_no_gap)
    x = torch.stack([F.pad(z, (0, max_len - len(z)), value=TokenType.END) for z in z_no_gap], dim=0).long()
    x_pad_mask = (x == TokenType.END)
    z_gap_mask = (z == TokenType.EPS)
    z_pad_mask = (z == TokenType.END)
    assert ((~x_pad_mask).sum(1) + z_gap_mask.sum(1)).equal((~z_pad_mask).sum(1))
    return x, x_pad_mask, z_gap_mask, z_pad_mask


### for sampling
def apply_ins_del_operations(
    xt: T["batch_size", "seq_len", "long"],
    ins_mask: T["batch_size", "seq_len", "bool"],
    del_mask: T["batch_size", "seq_len", "bool"],
    ins_tokens: T["batch_size", "seq_len", "long"],
    max_seq_len: int = 512,
) -> T["batch_size", "max_new_len", "long"]:
    """
    Apply insertion and deletion operations to a sequence xt based on the provided masks.
    """
    batch_size, seq_len = xt.shape
    device = xt.device

    # Handle simultaneous ins+del as substitutions
    replace_mask = ins_mask & del_mask
    xt_modified = xt.clone()
    xt_modified[replace_mask] = ins_tokens[replace_mask]

    # Update ins/del masks after handling replacements
    eff_ins_mask = ins_mask & ~replace_mask
    eff_del_mask = del_mask & ~replace_mask

    # Compute new lengths after applying ins/del operations
    xt_pad_mask = (xt == TokenType.END)     # (batch_size, seq_len)
    xt_seq_lens = (~xt_pad_mask).sum(dim=1) # (batch_size,)
    new_lengths = xt_seq_lens + eff_ins_mask.sum(dim=1) - eff_del_mask.sum(dim=1)
    max_new_len = int(new_lengths.max().item())

    if max_new_len <= 0:
        print(f"Unexpected max_new_len <= 0: {max_new_len}, did we delete everything?")
        return cast(
            T["batch_size", "max_new_len", "long"],
            torch.full((batch_size, 1), TokenType.END, dtype=xt.dtype, device=device),
        )

    # Pre-allocate result
    x_new = torch.full((batch_size, max_new_len), TokenType.END, dtype=xt.dtype, device=device)

    # Compute positions
    batch_idx = torch.arange(batch_size, device=device).unsqueeze(1)    # (batch_size, 1)
    pos_idx = torch.arange(seq_len, device=device).unsqueeze(0)         # (1, seq_len)
    cum_del = torch.cumsum(eff_del_mask.float(), dim=1)                 # num del up to & incl. current pos
    cum_ins = torch.cumsum(eff_ins_mask.float(), dim=1)                 # num ins up to & incl. current pos
    cum_ins_before = F.pad(cum_ins[:, :-1], (1, 0), value=0)            # num ins before current pos
    
    # Place non-deleted tokens
    new_pos = pos_idx + cum_ins_before - cum_del                            # new pos of tokens shifted by ins/del
    keep_mask = ~eff_del_mask & (new_pos >= 0) & (new_pos < max_new_len)    # tokens to keep (non-deleted)
    if keep_mask.any():
        x_new[batch_idx.expand(-1, seq_len)[keep_mask], new_pos[keep_mask].long()] = xt_modified[keep_mask]

    # Place insertions
    if eff_ins_mask.any():
        ins_pos = new_pos + 1                                               # insertions go 1 after new shifted pos
        ins_valid = eff_ins_mask & (ins_pos >= 0) & (ins_pos < max_new_len) # tokens to insert
        if ins_valid.any():
            x_new[batch_idx.expand(-1, seq_len)[ins_valid], ins_pos[ins_valid].long()] = ins_tokens[ins_valid]
    
    if max_new_len > max_seq_len:
        print(f"Warning: max_new_len {max_new_len} exceeds max_seq_len {max_seq_len}, truncating.")
        max_new_len = max_seq_len
    
    return cast(
        T["batch_size", "max_new_len", "long"],
        x_new[:, :max_new_len],
    )


def get_adaptive_h(h: float, t: torch.Tensor, scheduler: KappaScheduler):
    coeff = (1 - scheduler(t)) / scheduler.derivative(t)
    _h = h * torch.ones_like(t, device=t.device)
    h_adapt = torch.minimum(_h, coeff)
    return h_adapt


def random_sub(x: Tensor, rate: float):
    """randomly substitute some tokens of x based on the substitution rate
    """
    to_substitute = torch.rand_like(x.float()) < rate
    # do not substitute START tokens
    to_substitute[x == TokenType.START] = False
    x = torch.where(to_substitute, torch.randint_like(x, high=TokenType.RXN_MAX + 1), x)
    return x
